server:
  port: 9004

spring:
  application:
    name: analysis-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # Connect to order DB by default, but we will access other DBs via explicit table names
    url: jdbc:mysql://localhost:3306/supermarket_order?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: "123456"
